### PR TITLE
Adding Donut Danger game to Russian Roulette script

### PR DESCRIPTION
**Pull request by Battatta**
The Donut Danger game will be added to the script. Donut Danger is a non-permadeath version of Russian Roulette with its own fluff text.

### CODE REVIEW

**Comment by sebastianbarfurth** [comment]
Well, this is impressive.

**Comment by joriskcf** [comment]
I think this PR was intended for my fork.

**Comment by edwardslabs** [comment]
If it wasn't please resubmit from a clean branch.

**Comment by sebastianbarfurth** [comment]
Makes more sense, considering it also has merge conflicts. Closed.

**Comment by Battatta** [comment]
Yes, it was intented for joriskcf's fork.

**Pull request closed without merging**
